# Form implementation generated from reading ui file 'SSIS.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SSIS(object):
    def setupUi(self, SSIS):
        SSIS.setObjectName("SSIS")
        SSIS.resize(801, 600)
        SSIS.setMinimumSize(QtCore.QSize(801, 600))
        SSIS.setMaximumSize(QtCore.QSize(801, 600))
        SSIS.setMouseTracking(False)
        SSIS.setStyleSheet("background-color:rgb(34, 40, 49)")
        SSIS.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=SSIS)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color:rgb(34, 40, 49)")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.studentTab = QtWidgets.QWidget()
        self.studentTab.setObjectName("studentTab")
        self.studentLineEdit = QtWidgets.QLineEdit(parent=self.studentTab)
        self.studentLineEdit.setGeometry(QtCore.QRect(20, 80, 741, 22))
        self.studentLineEdit.setStyleSheet("background-color: rgb(238, 238, 238)")
        self.studentLineEdit.setText("")
        self.studentLineEdit.setMaxLength(20)
        self.studentLineEdit.setObjectName("studentLineEdit")
        self.deleteButtonStudent = QtWidgets.QPushButton(parent=self.studentTab)
        self.deleteButtonStudent.setGeometry(QtCore.QRect(420, 20, 341, 41))
        self.deleteButtonStudent.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.deleteButtonStudent.setObjectName("deleteButtonStudent")
        self.studentTable = QtWidgets.QTableView(parent=self.studentTab)
        self.studentTable.setGeometry(QtCore.QRect(20, 120, 741, 411))
        self.studentTable.setAutoFillBackground(False)
        self.studentTable.setStyleSheet("background-color: rgb(238, 238, 238)")
        self.studentTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.studentTable.setObjectName("studentTable")
        headers = ["StudentID", "Name", "Gender", "YearLevel", "CourseCode"]
        self.modelStudent.setHorizontalHeaderLabels(headers)
        self.addButtonStudent = QtWidgets.QPushButton(parent=self.studentTab)
        self.addButtonStudent.setGeometry(QtCore.QRect(20, 20, 341, 41))
        self.addButtonStudent.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.addButtonStudent.setObjectName("addButtonStudent")
        self.tabWidget.addTab(self.studentTab, "")
        self.courseTab = QtWidgets.QWidget()
        self.courseTab.setObjectName("courseTab")
        self.courseLineEdit = QtWidgets.QLineEdit(parent=self.courseTab)
        self.courseLineEdit.setGeometry(QtCore.QRect(20, 80, 741, 22))
        self.courseLineEdit.setStyleSheet("background-color: rgb(238, 238, 238)")
        self.courseLineEdit.setText("")
        self.courseLineEdit.setMaxLength(20)
        self.courseLineEdit.setObjectName("courseLineEdit")
        self.addButtonCourse = QtWidgets.QPushButton(parent=self.courseTab)
        self.addButtonCourse.setGeometry(QtCore.QRect(20, 20, 341, 41))
        self.addButtonCourse.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.addButtonCourse.setObjectName("addButtonCourse")
        self.deleteButtonCourse = QtWidgets.QPushButton(parent=self.courseTab)
        self.deleteButtonCourse.setGeometry(QtCore.QRect(420, 20, 341, 41))
        self.deleteButtonCourse.setStyleSheet("background-color:rgb(0, 173, 181);\n"
"font: 87 8pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.deleteButtonCourse.setObjectName("deleteButtonCourse")
        self.courseTable = QtWidgets.QTableView(parent=self.courseTab)
        self.courseTable.setGeometry(QtCore.QRect(20, 120, 741, 411))
        self.courseTable.setAutoFillBackground(False)
        self.courseTable.setStyleSheet("background-color: rgb(238, 238, 238)")
        self.courseTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.courseTable.setObjectName("courseTable")
        self.tabWidget.addTab(self.courseTab, "")
        SSIS.setCentralWidget(self.centralwidget)

        self.retranslateUi(SSIS)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SSIS)

    def retranslateUi(self, SSIS):
        _translate = QtCore.QCoreApplication.translate
        SSIS.setWindowTitle(_translate("SSIS", "MainWindow"))
        self.studentLineEdit.setPlaceholderText(_translate("SSIS", "Input Student ID For Searching"))
        self.deleteButtonStudent.setText(_translate("SSIS", "DELETE"))
        self.addButtonStudent.setText(_translate("SSIS", "ADD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.studentTab), _translate("SSIS", "STUDENT"))
        self.courseLineEdit.setPlaceholderText(_translate("SSIS", "Input Course Code For Searching"))
        self.addButtonCourse.setText(_translate("SSIS", "ADD"))
        self.deleteButtonCourse.setText(_translate("SSIS", "DELETE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.courseTab), _translate("SSIS", "COURSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SSIS = QtWidgets.QMainWindow()
    ui = Ui_SSIS()
    ui.setupUi(SSIS)
    SSIS.show()
    sys.exit(app.exec())
